spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    include: secret
