spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    include: secret

com:
  kobot:
    query:
      cache:
        threshold: 0.8
logging:
  level:
    com.kobot.backend: debug