spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    include: secret


  datasource:
    url: jdbc:mysql://localhost:3308/crawlingdb
    username: root
    password: publiko
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: create-drop
      show-sql: true
